[package]
name = "speakturbo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
ureq = "2"
rodio = { version = "0.17", default-features = false, features = ["wav"] }
anyhow = "1"
dirs = "5"

[profile.release]
lto = true
codegen-units = 1
strip = true
